server:
  port: 8082
spring:
  application:
    name: PaymentService
  datasource:
    url: jdbc:mysql://localhost:3306/ironbank?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 2222
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: ironbank
jwt:
  secret: 5ff4b0c9b2a356bd294ff36829610718dc053cd1fb66349f353f25d1cf7ce0697792f7352652ec46ea95f5875d93ae5e36e3c1b7d2eccf151aef99d0ac56ca2b